alias ga='git add .'
alias gaa='git add .'
alias gcm='git commit -m '
alias gc='git commit'
alias gd='git diff'
alias gi='git init'
alias gpll='git pull'
alias gpsh='git push'
alias gs='git status'
alias gss='git status -s'
alias grv='git remote -v'
alias gittree='git log --graph --full-history --all --pretty=format:"%h%x09%d%x20%s"'
