# Inserts a blank line between shell prompts
add_newline = false


# Change command timeout from 500 to 1000 ms
command_timeout = 1000
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 1000

# Make prompt a single line instead of two lines
[line_break]
disabled = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)

[battery.display] # discharging_symbol when capacity is between 0% and 20%
threshold = 20

# Changes \ as path separator in Windows, always use / please.
[directory]
use_os_path_sep	= false
