# Inserts a blank line between shell prompts
add_newline = false
# Change command timeout from 500 to 1000 ms
command_timeout = 1000
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 1000
# Custom Format with the time in the first line 
format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$time\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""


# ~/.config/starship.toml

[time]
disabled = false
time_format = "%R"

[package]
disabled=true

# Make prompt a single line instead of two lines
[line_break]
disabled = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)

[battery.display] # discharging_symbol when capacity is between 0% and 20%
threshold = 20

# Changes \ as path separator in Windows, always use / please.
[directory]
use_os_path_sep	= false
